services:
  announcement-service-db:
    image: postgres:14-alpine
    restart: always
    container_name: announcement-service-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: announcement_service_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "announcement_service_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - custom_network

  user-service-db:
    image: postgres:14-alpine
    restart: always
    container_name: user-service-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "user_service_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - custom_network

  mail-campaign-system-rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    container_name: mail-campaign-system-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - custom_network

  announcement-service:
    image: announcement-service:latest
    restart: always
    container_name: announcement-service
    ports:
      - "8090:8090"
    build:
      context: ./announcement-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://announcement-service-db:5432/announcement_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://announcement-service-db:5432/announcement_service_db
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: mail-campaign-system-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      announcement-service-db:
        condition: service_healthy
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  user-service:
    image: user-service:latest
    restart: always
    container_name: user-service
    ports:
      - "8095:8095"
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: postgres
    depends_on:
      user-service-db:
        condition: service_healthy
    networks:
      - custom_network

  mail-fanout-service:
    image: mail-fanout-service:latest
    restart: always
    container_name: mail-fanout-service
    build:
      context: ./mail-fanount-service
      dockerfile: Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: mail-campaign-system-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      USERSERVICE_URL: http://user-service:8095
    depends_on:
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  fanout-worker:
    image: fanout-worker:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    environment:
      SPRING_RABBITMQ_HOST: mail-campaign-system-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    build:
      context: ./fanout-worker
      dockerfile: Dockerfile
    depends_on:
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: no
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    networks:
      - custom_network


networks:
  custom_network:
    driver: bridge