services:
  announcement-service-db:
    image: postgres:14-alpine
    container_name: announcement-service-db
    extends:
      service: database-common
      file: common-config.yml
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "announcement_service_db" ]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: announcement_service_db
    volumes:
      - announcement-service-db-data:/var/lib/postgresql/data

  user-service-db:
    image: postgres:14-alpine
    container_name: user-service-db
    extends:
      service: database-common
      file: common-config.yml
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "user_service_db" ]
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_service_db
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

  mail-service-db:
    image: postgres:14-alpine
    container_name: mail-service-db
    extends:
      service: database-common
      file: common-config.yml
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "mail_service_db" ]
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mail_service_db
    volumes:
      - mail-service-db-data:/var/lib/postgresql/data

  analytics-service-db:
    image: postgres:14-alpine
    container_name: analytics-service-db
    extends:
      service: database-common
      file: common-config.yml
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "analytics_service_db" ]
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: analytics_service_db
    volumes:
      - analytics-service-db-data:/var/lib/postgresql/data

  mail-campaign-system-rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: always
    container_name: mail-campaign-system-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    networks:
      - custom_network

  announcement-service:
    image: mostafaosama/announcement-service:latest
    restart: always
    container_name: announcement-service
    extends:
      service: service-common
      file: common-config.yml
    ports:
      - "8090:8090"
    build:
      context: ./announcement-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://announcement-service-db:5432/announcement_service_db
      SPRING_LIQUIBASE_URL: jdbc:postgresql://announcement-service-db:5432/announcement_service_db
    depends_on:
      announcement-service-db:
        condition: service_healthy
      mail-campaign-system-rabbitmq:
        condition: service_healthy

  user-service:
    image: mostafaosama/user-service:latest
    restart: always
    container_name: user-service
    extends:
      service: service-common
      file: common-config.yml
    ports:
      - "8095:8095"
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
      SPRING_LIQUIBASE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
    depends_on:
      user-service-db:
        condition: service_healthy

  mail-fanout-service:
    image: mostafaosama/mail-fanout-service:latest
    restart: always
    container_name: mail-fanout-service
    extends:
      service: rabbitmq-connection-common
      file: common-config.yml
    build:
      context: ./mail-fanount-service
      dockerfile: Dockerfile
    environment:
      USERSERVICE_URL: http://user-service:8095
    depends_on:
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  fanout-worker:
    image: mostafaosama/fanout-worker:latest
    restart: always
    container_name: fanout-worker
    extends:
      service: rabbitmq-connection-common
      file: common-config.yml
    environment:
      CONSUMER_PREFETCH: 50
      CONSUMER_CONCURRENCY: 3
    build:
      context: ./fanout-worker
      dockerfile: Dockerfile
    depends_on:
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  mail-service:
    image: mostafaosama/mail-service:latest
    container_name: mail-service
    restart: always
    extends:
      service: rabbitmq-connection-common
      file: common-config.yml
    environment:
      CONSUMER_PREFETCH: 200
      CONSUMER_CONCURRENCY: 6
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    depends_on:
      mail-campaign-system-rabbitmq:
        condition: service_healthy
    networks:
      - custom_network

  analytics-service:
    image: mostafaosama/analytics-service:latest
    restart: always
    container_name: analytics-service
    extends:
      service: service-common
      file: common-config.yml
    ports:
      - "8099:8099"
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://analytics-service-db:5432/analytics_service_db
      SPRING_LIQUIBASE_URL: jdbc:postgresql://analytics-service-db:5432/analytics_service_db
      SPRING_RABBITMQ_STREAM_HOST: mail-campaign-system-rabbitmq
    depends_on:
      analytics-service-db:
        condition: service_healthy

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: no
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  announcement-service-db-data:
  user-service-db-data:
  mail-service-db-data:
  analytics-service-db-data:

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management,rabbitmq_stream]."