server:
  port: 8191

spring:
  application:
    name: fanout-worker

  cloud:
    function:
      definition: fanOutTaskConsumer
    stream:
      rabbit:
        bindings:
          fanOutTaskConsumer-in-0:
            consumer:
              prefetch: ${CONSUMER_PREFETCH:50}

      bindings:
        fanOutTaskConsumer-in-0:
          destination: fanout_tasks
          group: ${spring.application.name}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY:1}
            instance-count: 3

        fanOutTaskConsumer-out-0:
          destination: mails
# TODO: Work on partitioning
#          producer:
#            partition-key-expression: headers['partitionKey']
#            partition-count: 8
#            required-groups:
#              - mail-service