server:
  port: 9095

app:
  mail:
    dlq-cycles-before-park: 3

spring:
  application:
    name: mail-service

  cloud:
    function:
      definition: mailConsumer

    stream:
      rabbit:
        bindings:
          mailConsumer-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              dlq-ttl: 20000
              dlq-dead-letter-exchange: ""
              dlq-dead-letter-routing-key: "mails.${spring.application.name}"
              prefetch: ${CONSUMER_PREFETCH:200}

      bindings:
        mailConsumer-in-0:
          destination: mails
          group: ${spring.application.name}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY:1}

        parkingLot-out-0:
          destination: parking-lot
          producer:
            required-groups: ${spring.application.name}

        mailOutcome-out-0:
          destination: mails_outcomes
          group: "analytics-service"