server:
  port: 8088

spring:
  application:
    name: "trip-service"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mail_campaign_system
    username: postgres
    password: 1234

  liquibase:
    changelog: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/mail_campaign_system
    user: postgres
    password: 1234

  cloud:
    function:
      definition: tripEventCreated
    stream:
      bindings:
        tripEventCreated-in-0:
          destination: TripCreatedEvent-out-0
          group: ${spring.application.name}
        TripCreatedEvent-out-0:
          destination: TripCreatedEvent-out-0
